apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-deployment-operator-controller-manager
  namespace: model-deployment-operator-system
  labels:
    app.kubernetes.io/name: model-deployment-operator
    app.kubernetes.io/component: controller-manager
