//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
}

func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BenchmarkResult) DeepCopyInto(out *BenchmarkResult) {
	*out = *in
}

func (in *BenchmarkResult) DeepCopy() *BenchmarkResult {
	if in == nil {
		return nil
	}
	out := new(BenchmarkResult)
	in.DeepCopyInto(out)
	return out
}

func (in *BenchmarkSpec) DeepCopyInto(out *BenchmarkSpec) {
	*out = *in
}

func (in *BenchmarkSpec) DeepCopy() *BenchmarkSpec {
	if in == nil {
		return nil
	}
	out := new(BenchmarkSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
}

func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelDeployment) DeepCopyInto(out *ModelDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ModelDeployment) DeepCopy() *ModelDeployment {
	if in == nil {
		return nil
	}
	out := new(ModelDeployment)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelDeploymentList) DeepCopyInto(out *ModelDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ModelDeploymentList) DeepCopy() *ModelDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentList)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelDeploymentSpec) DeepCopyInto(out *ModelDeploymentSpec) {
	*out = *in
	out.Resources = in.Resources
	out.Service = in.Service
	out.Ingress = in.Ingress
	out.Autoscaling = in.Autoscaling
	out.Observability = in.Observability
	out.Benchmark = in.Benchmark
	out.RAG = in.RAG
	out.Secrets = in.Secrets
}

func (in *ModelDeploymentSpec) DeepCopy() *ModelDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelDeploymentStatus) DeepCopyInto(out *ModelDeploymentStatus) {
	*out = *in
	if in.LastBenchmark != nil {
		in, out := &in.LastBenchmark, &out.LastBenchmark
		*out = new(BenchmarkResult)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ModelDeploymentStatus) DeepCopy() *ModelDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ModelDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
}

func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RAGSpec) DeepCopyInto(out *RAGSpec) {
	*out = *in
	out.VectorDatabase = in.VectorDatabase
}

func (in *RAGSpec) DeepCopy() *RAGSpec {
	if in == nil {
		return nil
	}
	out := new(RAGSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
}

func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretSpec) DeepCopyInto(out *SecretSpec) {
	*out = *in
}

func (in *SecretSpec) DeepCopy() *SecretSpec {
	if in == nil {
		return nil
	}
	out := new(SecretSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
}

func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VectorDatabaseSpec) DeepCopyInto(out *VectorDatabaseSpec) {
	*out = *in
}

func (in *VectorDatabaseSpec) DeepCopy() *VectorDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(VectorDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}
