image:
  repository: ghcr.io/henishpatel1214/model-deployment-operator
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

serviceAccount:
  create: true
  name: model-deployment-operator-controller-manager

metrics:
  enabled: true
  serviceMonitor:
    enabled: false
    interval: 30s

leaderElection:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
